// Invented class for developing the print sheet. No real student data.
window.ROSTER_DATA = {
  course: 'Mock 3D Design - Period 3',
  assignment: 'Keychain Print',
  students: [
    { name: 'Avery Adams',     files: ['red_dragon.stl'] },
    { name: 'Blake Baker',     files: ['Bleu Vase.stl'] },
    { name: 'Casey Carter',    files: ['gren frog.stl'] },
    { name: 'Devon Diaz',      files: ['PurpleRobot.stl'] },
    { name: 'Emery Evans',     files: ['crown.stl'] },
    { name: 'Finley Foster',   files: ['Orang cat.stl'] },
    { name: 'Gray Garcia',     files: ['yelow duck.stl'] },
    { name: 'Harper Hill',     files: ['grey_tank.stl'] },
    { name: 'Indigo Ito',      files: ['black and white panda.stl'] },
    { name: 'Jordan Jones',    files: ['Mighty Sango.stl'] },
    { name: 'Kai Kim',         files: ['pnk heart.stl', 'blue_heart_v2.stl'] },
    { name: 'Logan Lopez',     files: ['reddragon.stl'] },
    { name: 'Morgan Moore',    files: ['block tower.stl'] },
    { name: 'Noor Nguyen',     files: ['Rainbow Snake.stl'] },
    { name: 'Oakley Ortiz',    files: ['pruple_whale.stl'] },
    { name: 'Parker Patel',    files: [] },
    { name: 'Quinn Quinn',     files: ['GOLD_trophy.stl'] },
    { name: 'Reese Reyes',     files: ['wite_ghost.stl'] },
    { name: 'Sage Singh',      files: ['team logo.stl'] },
    { name: 'Tatum Taylor',    files: [] },
    { name: 'Uma Underwood',   files: ['d1p2 john fitz kennedy project #3 Orange.stl'] },
    { name: 'Val Vasquez',     files: ['period 3 keychain assignment final version my cool dragon head Green.stl'] },
  ],
};
